# Generated by Django 3.1.3 on 2020-11-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=64, unique=True)),
                ('region', models.CharField(max_length=128)),
            ],
        ),
    ]
