# Generated by Django 3.1.3 on 2020-11-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
